### PR TITLE
Fixed a bug with TransferUploadService to handle unlocated recipients during transfers.

### PR DESCRIPTION
**Pull request by tacosontitan**
This PR fixes bug #547

### CODE REVIEW

**Comment by tacosontitan** [comment]
This has incorrect logic; somehow the `not` was dropped. Updating now.

**Comment by Jack-Edwards** [comment]
@tacosontitan Would you mind rebasing this to the `stable` branch?

**Comment by tacosontitan** [comment]
I'm still new to `rebase`; so I *believe* it's done, but if not let me know and I'll adjust further if needed.

**Comment by Jack-Edwards** [comment]
Looks good on my end.  Thank you!

**Review by Jack-Edwards — APPROVED** [review]
Perfect.

**Pull request merged**
