### PR TITLE
Removed _modalClassShow from ModalBehavior

### PR DESCRIPTION
**Pull request by aarondunn21**
Solved issue #508 by removing `_modalClassShow`, running unit tests, and verifying the front-end for no changes with docker

### CODE REVIEW

**Comment by Jack-Edwards** [comment]
Thank you very much.  I'll verify this shortly.

**Comment by aarondunn21** [comment]
> It looks like `ModalClass` can also be removed from the .razor and the .razor.cs files. Would you want to take care of that here a well?

Yes, I will take a look at those.

**Comment by aarondunn21** [comment]
I have removed `ModalClass` and verified front-end functionality remains the same.

**Review by Jack-Edwards — APPROVED** [review]
Looks good.  Thank you.

**Pull request merged**
